uploads = []

[[generated]]
id = "u31TMP3FsIuXRXVtDleqN"
uri = "file://artifacts/lito/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BkPw1398BykMJKxDZDL81"
uri = "file://artifacts/lito/assets/images/splash.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5OeF2hMG98ZZ1GFXuPtOY"
uri = "file://artifacts/lito/assets/images/profile1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "y1nKYpy8o_US-SH4QpHXJ"
uri = "file://artifacts/lito/assets/images/profile2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2Gs9w4swSp3hfJgZKcaFi"
uri = "file://artifacts/lito/assets/images/profile3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NhD2ekEa6FjnZXPe-DNZS"
uri = "file://artifacts/lito/assets/images/profile4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "314wnNmQcQQW_HO-JoFRS"
uri = "file://artifacts/lito/assets/images/profile5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "L885DOOd34AGgtfpbyMBd"
uri = "file://artifacts/lito/assets/images/profile6.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "HlgGZxsqtK1Jypix25e4E"
uri = "file://lito-trust-safety-policy.md"
type = "text"
title = "Lito Trust & Safety Policy Framework v1.0"

[[outputs]]
id = "qS5VqGlpEQt4aj9igXnAa"
uri = "file://lito-analytics-kpi.md"
type = "text"
title = "Lito Analytics & KPI Instrumentation v1.0"

[[outputs]]
id = "RLZYz-MwddCrmGWEKMllM"
uri = "file://lito-closed-beta-plan.md"
type = "text"
title = "Lito Closed Beta Test Plan v1.0"

[[outputs]]
id = "kFjc9vdoqu1HKg_tk6FsV"
uri = "file://lito-prelaunch-plan.md"
type = "text"
title = "Lito Pre-Launch Improvement Plan v1.0"

[[outputs]]
id = "043tAX6ZGCb_8Z00tO9wN"
uri = "file://artifacts/admin/public/lito-source.tar.gz"
type = "unspecified"
title = "Lito 소스코드 (tar.gz)"
